FROM php:8.0-fpm

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

RUN docker-php-ext-install pdo_mysql

WORKDIR /var/www/html
COPY magazzino/ /var/www/html/

COPY docker/php/db_migrate.php /usr/local/bin/db_migrate.php
COPY docker/php/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["php-fpm"]
